name: Daily Runner Weather Bot

on: 
    push:

jobs:
    Daily-Run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: pip install -r requirements.txt
            -name: install pywin
              run: python -m pip install --upgrade pywin32
            - name: Run App
              run: python app.py